"""Canonical chart scene model for chart rendering/export."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class MetadataScene:
    show_name: str = ""
    dop: str = ""
    font_size: float = 12.0
    offset_x: float = 0.0
    offset_y: float = 0.0
    camera_model: str = ""
    recording_mode: str = ""
    framing_dimensions: str = ""
    framing_aspect_ratio: str = ""


@dataclass
class BurnInScene:
    title: str = ""
    director: str = ""
    dop: str = ""
    sample_text_1: str = ""
    sample_text_2: str = ""
    font_size: float = 12.0


@dataclass
class LogoScene:
    text: str = "FDL Tool"
    position: str = "center"
    image_base64: str = ""
    scale: float = 1.0
    offset_x: float = 0.0
    offset_y: float = 0.0


@dataclass
class FramelineScene:
    label: str = ""
    width: float = 0.0
    height: float = 0.0
    color: str = "#FF3B30"
    h_align: str = "center"
    v_align: str = "center"
    anchor_x: float | None = None
    anchor_y: float | None = None
    protection_width: float | None = None
    protection_height: float | None = None
    protection_anchor_x: float | None = None
    protection_anchor_y: float | None = None
    framing_intent: str = ""
    style: str = "full_box"
    style_length: float = 0.08


@dataclass
class ChartScene:
    canvas_width: int = 4096
    canvas_height: int = 2160
    title: str = "Framing Chart"
    show_labels: bool = True
    padding: int = 60
    effective_width: int | None = None
    effective_height: int | None = None
    show_crosshairs: bool = False
    show_grid: bool = False
    grid_spacing: int = 100
    anamorphic_squeeze: float = 1.0
    show_squeeze_circle: bool = False
    show_center_marker: bool = False
    show_format_arrows: bool = False
    print_safe_margin_percent: float = 0.0
    show_siemens_stars: bool = False
    siemens_star_size: str = "small"
    show_chart_markers: bool = False
    background_theme: str = "dark"
    layers: dict[str, bool] = field(
        default_factory=lambda: {
            "canvas": True,
            "effective": True,
            "protection": True,
            "framing": True,
        }
    )
    framelines: list[FramelineScene] = field(default_factory=list)
    metadata: MetadataScene | None = None
    burn_in: BurnInScene | None = None
    logo: LogoScene | None = None
    description: str = "Generated by FDL Tool Chart Generator"
    dpi: int = 150

    @classmethod
    def from_params(cls, params: dict[str, Any], default_colors: list[str]) -> ChartScene:
        layers = params.get("layers", {})
        scene = cls(
            canvas_width=int(params.get("canvas_width", 4096)),
            canvas_height=int(params.get("canvas_height", 2160)),
            title=str(params.get("title", "Framing Chart")),
            show_labels=bool(params.get("show_labels", True)),
            padding=int(params.get("padding", 60)),
            effective_width=params.get("effective_width"),
            effective_height=params.get("effective_height"),
            show_crosshairs=bool(params.get("show_crosshairs", False)),
            show_grid=bool(params.get("show_grid", False)),
            grid_spacing=int(params.get("grid_spacing", 100)),
            anamorphic_squeeze=float(params.get("anamorphic_squeeze", 1.0)),
            show_squeeze_circle=bool(params.get("show_squeeze_circle", False)),
            show_center_marker=bool(params.get("show_center_marker", False)),
            show_format_arrows=bool(params.get("show_format_arrows", False)),
            print_safe_margin_percent=float(params.get("print_safe_margin_percent", 0.0)),
            show_siemens_stars=bool(params.get("show_siemens_stars", False)),
            siemens_star_size=str(params.get("siemens_star_size", "small")),
            show_chart_markers=bool(params.get("show_chart_markers", False)),
            background_theme=str(params.get("background_theme", "dark")),
            layers={
                "canvas": bool(layers.get("canvas", True)),
                "effective": bool(layers.get("effective", True)),
                "protection": bool(layers.get("protection", True)),
                "framing": bool(layers.get("framing", True)),
            },
            description=str(params.get("description", "Generated by FDL Tool Chart Generator")),
            dpi=int(params.get("dpi", 150)),
        )

        metadata = params.get("metadata")
        if isinstance(metadata, dict):
            scene.metadata = MetadataScene(
                show_name=str(metadata.get("show_name", "")),
                dop=str(metadata.get("dop", "")),
                font_size=float(metadata.get("font_size", 12.0)),
                offset_x=float(metadata.get("offset_x", 0.0)),
                offset_y=float(metadata.get("offset_y", 0.0)),
                camera_model=str(metadata.get("camera_model", "")),
                recording_mode=str(metadata.get("recording_mode", "")),
                framing_dimensions=str(metadata.get("framing_dimensions", "")),
                framing_aspect_ratio=str(metadata.get("framing_aspect_ratio", "")),
            )
        burn_in = params.get("burn_in")
        if isinstance(burn_in, dict):
            scene.burn_in = BurnInScene(
                title=str(burn_in.get("title", "")),
                director=str(burn_in.get("director", "")),
                dop=str(burn_in.get("dop", "")),
                sample_text_1=str(burn_in.get("sample_text_1", "")),
                sample_text_2=str(burn_in.get("sample_text_2", "")),
                font_size=float(burn_in.get("font_size", 12.0)),
            )
        logo = params.get("logo")
        if isinstance(logo, dict):
            scene.logo = LogoScene(
                text=str(logo.get("text", "FDL Tool")),
                position=str(logo.get("position", "center")),
                image_base64=str(logo.get("image_base64", "")),
                scale=float(logo.get("scale", 1.0)),
                offset_x=float(logo.get("offset_x", 0.0)),
                offset_y=float(logo.get("offset_y", 0.0)),
            )

        framelines = params.get("framelines", [])
        for i, fl in enumerate(framelines):
            if not isinstance(fl, dict):
                continue
            scene.framelines.append(
                FramelineScene(
                    label=str(fl.get("label", "")),
                    width=float(fl.get("width", scene.canvas_width)),
                    height=float(fl.get("height", scene.canvas_height)),
                    color=str(fl.get("color", default_colors[i % len(default_colors)])),
                    h_align=str(fl.get("h_align", "center")),
                    v_align=str(fl.get("v_align", "center")),
                    anchor_x=fl.get("anchor_x"),
                    anchor_y=fl.get("anchor_y"),
                    protection_width=fl.get("protection_width"),
                    protection_height=fl.get("protection_height"),
                    protection_anchor_x=fl.get("protection_anchor_x"),
                    protection_anchor_y=fl.get("protection_anchor_y"),
                    framing_intent=str(fl.get("framing_intent", "")),
                    style=str(fl.get("style", "full_box")),
                    style_length=float(fl.get("style_length", 0.08)),
                )
            )

        return scene
